# Copyright 2018, Marcos Ziegler
# All rights reserved.
#
# This file is part of Workspace.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

vfs_PATH := modules/lpc4337_m4/vfs

vfs_SRC_FILES += $(wildcard $(vfs_PATH)/src/*.c) \
                 $(wildcard $(vfs_PATH)/src/fatfs/src/*.c) \
                 $(wildcard $(vfs_PATH)/src/lwip_threads/*.c)

vfs_SRC_FOLDERS += modules/lpc4337_m4/vfs/src \
                   modules/lpc4337_m4/vfs/src/fatfs/src \
									 modules/lpc4337_m4/vfs/src/lwip_threads

vfs_INC_FOLDERS += modules/lpc4337_m4/vfs/inc \
                   modules/lpc4337_m4/vfs/inc/implement \
                   modules/lpc4337_m4/vfs/inc/fatfs/inc \
									 modules/lpc4337_m4/vfs/inc/lwip_threads

# usb host symbol
SYMBOLS += -DUSB_HOST_ONLY
LFLAGS += --specs=nosys.specs -lnosys
